---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-channel
  namespace: samples
  labels:
    app: sender-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender-channel
  template:
    metadata:
      labels:
        app: sender-channel
    spec:
      containers:
      - name: sender-channel
        image: samples/sender-channel
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: "EventChannel__BaseUrl"
          value: "http://simple-channel-kn-channel.samples.svc.cluster.local"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-channel
  namespace: samples
  labels:
    app: receiver-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-channel
  template:
    metadata:
      labels:
        app: receiver-channel
    spec:
      containers:
      - name: receiver-channel
        image: samples/receiver-channel
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: sender-channel
  namespace: samples
spec:
  selector:
    app: sender-channel
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: receiver-channel
  namespace: samples
spec:
  selector:
    app: receiver-channel
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sender-channel
  namespace: samples
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /send/message
spec:
  ingressClassName: "nginx"
  rules:
  - host: "samples.lvh.me"
    http:
      paths:
      - pathType: Prefix
        path: "/channel/sender"
        backend:
          service:
            name: sender-channel
            port:
              number: 80

---
apiVersion: messaging.knative.dev/v1beta1
kind: KafkaChannel
metadata:
  name: simple-channel
  namespace: samples
spec:
  numPartitions: 3
  replicationFactor: 1

---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: receiver-channel
  namespace: samples
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: KafkaChannel
    name: simple-channel
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: receiver-channel
    uri: "/receive/message"