---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1
spec:
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: perf-test/svc1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  selector:
    app: svc1
  ports:
  - name: http
    targetPort: 8080
    port: 38081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svc1
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: "api.lvh.me"
    http:
      paths:
      - path: /svc1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: svc1
            port:
              number: 38081