---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2
spec:
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
      - name: svc2
        image: perf-test/svc2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: svc2
spec:
  selector:
    app: svc2
  ports:
  - name: http
    targetPort: 8080
    port: 38080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svc2
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: "api.lvh.me"
    http:
      paths:
      - path: /svc2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: svc2
            port:
              number: 38080