apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: grafana
    port: 3000
    targetPort: grafana
  - name: otel-grpc
    port: 4317
    targetPort: otel-grpc
  - name: otel-http
    port: 4318
    targetPort: otel-http