---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel
  namespace: monitoring
  labels:
    app: otel
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      logging:
      otlp/jaeger:
        endpoint: "jaeger.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
      elasticsearch:
        endpoints: [elasticsearch.monitoring.svc.cluster.local:9200]
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging, otlp/jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, prometheus]
        logs:
          receivers: [otlp]
          exporters: [logging, elasticsearch]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel
  namespace: monitoring
  labels:
    app: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
      - image: otel/opentelemetry-collector-contrib
        imagePullPolicy: Always
        name: otel
        ports:
        - containerPort: 4317
          name: otel-grpc
        - containerPort: 4318
          name: otel-http
        - containerPort: 8889
          name: prometheus
        - containerPort: 8888
          name: prom
        volumeMounts:
        - mountPath: /etc/otelcol-contrib/config.yaml
          name: otel-config
          readOnly: true
          subPath: config.yaml
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - configMap:
          defaultMode: 420
          name: otel
        name: otel-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel
  namespace: monitoring
  labels:
    app: otel
spec:
  selector:
    app: otel
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  - name: prometheus
    port: 8889
    targetPort: 8889
    protocol: TCP
  - name: prom
    port: 8888
    targetPort: 8888
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: "otel.lvh.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otel
            port:
              number: 4317
  - host: "otel-metrics.lvh.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otel
            port:
              number: 8889
---
