---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm
  namespace: monitoring
  labels:
    app: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      name: lgtm
      labels:
        app: lgtm
    spec:
      containers:
      - name: lgtm
        image: grafana/otel-lgtm:0.6.0
        ports:
        - name: grafana
          containerPort: 3000
        - name: otel-grpc
          containerPort: 4317
        - name: otel-http
          containerPort: 4318
        resources:
          requests:
            cpu: 100m
            memory: 500M
          limits:
            memory: 500M
---
apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: monitoring
spec:
  selector:
    app: lgtm
  ports:
  - name: grafana
    port: 3000
    targetPort: grafana
  - name: otel-grpc
    port: 4317
    targetPort: otel-grpc
  - name: otel-http
    port: 4318
    targetPort: otel-http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lgtm
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: "grafana.lvh.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lgtm
            port:
              number: 3000
---
