apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Root CA"
  secretName: root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.clusterIssuer.name }}-ca
    kind: ClusterIssuer
    group: cert-manager.io