---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: observability
  name: tempo
data:
  tempo.yaml: |-
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
            grpc:
            thrift_binary:
            thrift_compact:
        zipkin:
        otlp:
          protocols:
            http:
            grpc:
    ingester:
      max_block_duration: 5m
    compactor:
      compaction:
        block_retention: 1h
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: rancher-desktop
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://prometheus.observability.svc.cluster.local:9090/api/v1/write
            send_exemplars: true
    storage:
      trace:
        backend: s3
        wal:
          path: /tmp/tempo/wal
        s3:
          bucket: tempo
          endpoint: minio.storage.svc.cluster.local:9000
          access_key: tempo
          secret_key: supersecret
          insecure: true
    overrides:
      metrics_generator_processors: [service-graphs, span-metrics]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: observability
  name: tempo
spec:
  selector:
    matchLabels:
      app: tempo
  replicas: 1
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo
        args:
          - --config.file=/etc/tempo.yaml
        ports:
        - name: jaeger
          containerPort: 14268
        - name: tempo
          containerPort: 3200
        volumeMounts:
        - name: config
          mountPath: /etc/tempo.yaml
          subPath: tempo.yaml
      volumes:
      - name: config
        configMap:
          defaultMode: 420
          name: tempo
---
apiVersion: v1
kind: Service
metadata:
  namespace: observability
  name: tempo
spec:
  selector:
    app: tempo
  ports:
  - protocol: TCP
    port: 14268
    targetPort: 14268
    name: jaeger
  - protocol: TCP
    port: 3200
    targetPort: 3200
    name: tempo