apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/allow-direct-injection: "true"
---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: {{ .Release.Name }}-webhook-server-cert
#  namespace: {{ .Release.Namespace }}
#spec:
#  commonName: {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc
#  dnsNames:
#  - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
#  - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}.svc
#  - {{ .Release.Name }}-webhook-service.{{ .Release.Namespace }}
#  - {{ .Release.Name }}-webhook-service
#  issuerRef:
#    group: cert-manager.io
#    kind: ClusterIssuer
#    name: lvh-me
#  secretName: {{ .Release.Name}}-webhook-server-cert