---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgpool-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgB/rpNOfFtZB+BLvmR/rgdmHuTkFcH7y5HDsaj99ZNGqEGL8AX0arQS3W+XUfc3MCDGZ1HWfXVswf9nP4q1B4GcLwcXuGSeb7fS0ZrkWCJiKSz4zjT24T4H4+vQTbQooRr/WymeVaLtnwrI/nQt7hOK7nI6qGTjhFG6y4YzKnvNogo0MnJ2RY+I3jxutNSWjHuhXbmXVxdMhIGL2VcsW5055HkYmpp0nuQPtVXWgyRQfSdOMSqkoWgJiOYGeUfM3DrGJTgNVwCO1QUy1KGt0iWX5r20mvVP9VQmA0V62Ss75IHPyqwXacNYpWPQSxD9r+rH8uRpozYWitA1t4+HOcijrb/ggX5HifAZUtnWE0lVKd8qkzZFZxB1jurPh26/DfXNJruYRsjfLMBPFftuArzfsbfb/dRwP7Z8+Cy8GI9TZwgFzSh9L9fNLG/oWm17vRPatXZHTv2gs7mf+J7DWCzyy3EFhGJ6McaJl2cKRPthVKZU1klMTwFpTg+wmjLqCQ+67ad9qfV6l6DNsNkFwIjsGHSiCHWjRG0AW7LBT8IKQNxkktKq2mj3EQEicu/EJ997ivEhmA1dtdIRdTiom0qe+qvW55uaRBR31TjSBo16MnXxLAWqjRBj8Xi+1koGT9h7lrkWpjMU08VHWEBYG2GKZA8yUkLwWQqz5Ei7OSemef87gOwcvzzuX7oEcsP6Q5dXPXAxWo8vI1X/qCMmrG96
  template:
    metadata:
      creationTimestamp: null
      name: pgpool-secret
      namespace: keycloak
